language: node_js
node_js: 8

branches:
  only:
    - source

script: yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  fqdn: icefla.me
  on:
    branch: source
